{% set name = "fuzy-jon" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fuzy_jon-{{ version }}.tar.gz
  sha256: d57f75d4bc067b362eaf83b3f9199672cd0dadc8263470a169c9b374d5d89ff6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - poetry-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - json5

test:
  imports:
    - fuzzy_json
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/livingbio/fuzzy-json
  summary: 'Fuzzy-JSON is a compact Python package with no dependencies, designed to address the pesky JSONDecodeError that sometimes occurs when utilizing OpenAIs powerful call function.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
